version: 2

models:

  - name: stg_greenery__addresses
    description: "Staging Addresses view"

    columns:
      - name: address_id
        description: UUID for each unique address on platform

      - name: address
        description: The first few lines of the address
    
      - name: zip_code
        description: The zipcode of the address      
      
      - name: state
        description: State this delivery address is based in
    
      - name: country
        description: Country this delivery address is based in

  - name: stg_greenery__events
    description: "Staging Events view"

    columns:
      - name: event_id
        description: UUID of each unique event on the platform

      - name: session_id
        description: UUID of each browsing session on the platform which can contain many events   

      - name: user_id
        description: UUID of the user that this event is associated with        
      
      - name: event_type
        description: Type of event

      - name: page_url
        description: URL that the event happened on    

      - name: created_at_utc
        description: Timestamp of the event   

      - name: order_id
        description: If the event is specific to an order (mostly used for checkout)   

      - name: product_id
        description: If the event is specific to a product

  - name: stg_greenery__order_items
    description: "Staging Order Items view"

    columns:
      - name: order_id
        description:  OrderId of this order     

      - name: product_id
        description: ProductId of a single item in this order
      
      - name: quantity
        description: Number of units of the product in this order     

  - name: stg_greenery__orders
    description: "Staging Orders view"

    columns:
      - name: order_id
        description: UUID for each unique order on platform

      - name: promo_id
        description: PromoId if any was used in the order

      - name: user_id
        description: UserId of the user that placed this order   

      - name: address_id
        description: Delivery address for this order

      - name: created_at_utc
        description: Timestamp when the order was created

      - name: order_cost
        description: Dollar amount of the items in the order

      - name: shipping_cost
        description: Cost of shipping for the order

      - name: order_total
        description: Total cost of the order including shipping

      - name: tracking_id
        description: Tracking number for the order/package  
   
      - name: shipping_service
        description: Company that was used for shipping

      - name: estimated_delivery_at_utc
        description: Estimated date of delivery

      - name: delivered_at_utc
        description: Actual timestamp of delivery

      - name: order_status
        description: Status of the order

  - name: stg_greenery__products
    description: "Staging Products view"

    columns:

      - name: product_id
        description: UUID for each unique product on platform

      - name: product_name
        description: Name of the product

      - name: price
        description: Price of the product 

      - name: inventory_amount
        description: Amount of the inventory we have for this product   
 
  - name: stg_greenery__promos
    description: "Staging Promos view"

    columns:
      - name: promo_id
        description: Each unique promocode on platform      

      - name: discount_amount
        description: Absolute dollar amount that is given off with the code  

      - name: promo_status
        description: Is the promo code active or disabled               


  - name: stg_greenery__users
    description: "Staging Users view"

    columns:
      - name: user_id
        description: UUID for each unique user on platform

      - name: first_name
        description: First name of the user

      - name: last_name
        description: Last name of the user

      - name: email
        description: Email address of the user

      - name: phone_number
        description: Phone number of the user

      - name: created_at_utc
        description: Timestamp the user was created

      - name: update_at_utc
        description: Timestamp the user was last updated
        
      - name: address_id
        description: Default delivery address for the user